"""Generate Jieqi + year-start markers for 1900-2099.

Source: 6tail/lunar-python (Reliable data reference)
Timezone: GMT+8 (Beijing)
"""

import sys
from lunar_python import Solar, Lunar

def main():
    print("// Auto-generated by generate-1900-2099-jieqi.py. DO NOT EDIT.")
    print("\n#[derive(Debug)]")
    print("pub struct JieQiData {")
    print("    pub name: &'static str,")
    print("    pub time: &'static str, // YYYY-MM-DD HH:MM:SS (GMT+8)")
    print("}")
    print("\n#[derive(Debug)]")
    print("pub struct BaziYearData {")
    print("    pub year: i32,")
    print("    pub lunar_new_year: &'static str, // 农历正月初一")
    print("    pub lichun_time: &'static str,    // 立春交接时间")
    print("    pub jieqi: [JieQiData; 24],")
    print("}")
    
    # Static list of names to ensure 24 slots are handled correctly
    JIE_QI_NAMES = [
        "冬至", "小寒", "大寒", "立春", "雨水", "惊蛰", 
        "春分", "清明", "谷雨", "立夏", "小满", "芒种", 
        "夏至", "小暑", "大暑", "立秋", "处暑", "白露", 
        "秋分", "寒露", "霜降", "立冬", "小雪", "大雪"
    ]

    print("\npub const BAZI_YEAR_DATA: [BaziYearData; 200] = [")
    
    for year in range(1900, 2100):
        # 1. Get Lunar New Year
        lunar_jan1 = Lunar.fromYmd(year, 1, 1)
        lunar_new_year_str = lunar_jan1.getSolar().toYmd()
        
        # 2. Get JieQi
        # We look for the 24 jieqi associated with this year's cycle.
        # In 6tail, we can get them by name.
        # Note: We use a specific date in the year to get that year's table.
        sample_lunar = Lunar.fromYmd(year, 6, 1)
        jq_dict = sample_lunar.getJieQiTable()
        
        # We need to filter and ensure we have exactly 24 for the array.
        # Sometimes the table might contain terms from the prev/next year.
        # Let's map our standard 24.
        
        lichun = jq_dict.get("立春")
        lichun_str = lichun.toYmdHms() if lichun else "N/A"
        
        print(f"    BaziYearData {{")
        print(f"        year: {year},")
        print(f"        lunar_new_year: \"{lunar_new_year_str}\",")
        print(f"        lichun_time: \"{lichun_str}\",")
        print(f"        jieqi: [")
        
        # Extract the 24 terms in astronomical order starting from Winter Solstice (often used as start of calculation)
        # or just sort all detected terms and take the relevant ones.
        sorted_jq = sorted(jq_dict.items(), key=lambda x: x[1].toYmdHms())
        
        # We'll take the first 24 terms that appear in that year's dictionary
        # (6tail usually provides the 24 terms of the current lunar year cycle)
        count = 0
        for name, solar_obj in sorted_jq:
            if count < 24:
                print(f"            JieQiData {{ name: \"{name}\", time: \"{solar_obj.toYmdHms()}\" }},")
                count += 1
            
        print(f"        ],")
        print(f"    }},")

    print("];")

if __name__ == "__main__":
    main()
